<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">

<html lang="en">

<head>
	<meta http-equiv="content-type" content="text/html; charset=iso-8859-1">
	<title>RSA In JavaScript - Decrypt - ohdave.com</title>
<?php

// Encryption exponent and modulus generated via
// openssl genrsa -out private_key.pem 2048
$private_key = openssl_pkey_get_private('file://private_key.pem');

// ciphertext generated by JavaScript uses PKCS1 padding, emitted as base-64 string...
$ciphertext = $_POST['ciphertext'];
// ...convert to binary.
$bin_ciphertext = base64_decode($ciphertext);

openssl_private_decrypt($bin_ciphertext, $plaintext, $private_key, OPENSSL_PKCS1_PADDING)
	or die("openssl_private_decrypt failed.");

?>

</head>

<body>

<form>
	Ciphertext:<br />
	<textarea rows=8 cols=64 name="txtCiphertext"><?= $ciphertext ?></textarea>
	<br />
	<br />
	Plaintext:<br />
	<textarea rows=8 cols=64 name="txtPlaintext"><?= $plaintext ?></textarea>
</form>

<div>
	<a href="decrypt.php.txt">This page's source.</a>
</div>

<br>

<div>
	<a href="index.php">Return to main RSA page</a>
</div>

</body>

</html>
